# ADI/ADIF/ ADX Record strings
EOR ="EOR"
EOH = "EOH"
ADIF_VER = "ADIF_VER"
CREATED_TIMESTAMP = "CREATED_TIMESTAMP"
PROGRAMID = "PROGRAMID"
PROGRAMVERSION = "PROGRAMVERSION"

OTHER = "OTHER"
ADDRESS="ADDRESS"
ADDRESS_INTL="ADDRESS_INTL"
AGE="AGE"
ALTITUDE="ALTITUDE"
ANT_AZ="ANT_AZ"
ANT_EL="ANT_EL"
ANT_PATH="ANT_PATH"
ARRL_SECT="ARRL_SECT"
AWARD_GRANTED="AWARD_GRANTED"
AWARD_SUBMITTED="AWARD_SUBMITTED"
A_INDEX="A_INDEX"

BAND="BAND"
BAND_RX="BAND_RX"

CALL="CALL"
CHECK="CHECK"
CLASS="CLASS"
CLUBLOG_QSO_UPLOAD_DATE="CLUBLOG_QSO_UPLOAD_DATE"
CLUBLOG_QSO_UPLOAD_STATUS="CLUBLOG_QSO_UPLOAD_STATUS"
CNTY="CNTY"
COMMENT="COMMENT"
COMMENT_INTL="COMMENT_INTL"
CONT="CONT"
CONTACTED_OP="CONTACTED_OP"
CONTEST_ID="CONTEST_ID"
COUNTRY="COUNTRY"
COUNTRY_INTL="COUNTRY_INTL"
CQZ="CQZ"
CREDIT_SUBMITTED="CREDIT_SUBMITTED"
CREDIT_GRANTED="CREDIT_GRANTED"

DARC_DOK="DARC_DOK"
DISTANCE="DISTANCE"
DXCC="DXCC"

EMAIL="EMAIL"
EQ_CALL="EQ_CALL"
EQSL_QSLRDATE="EQSL_QSLRDATE"
EQSL_QSLSDATE="EQSL_QSLSDATE"
EQSL_QSL_RCVD="EQSL_QSL_RCVD"
EQSL_QSL_SENT="EQSL_QSL_SENT"

FISTS="FISTS"
FISTS_CC="FISTS_CC"
FORCE_INIT="FORCE_INIT"
FREQ="FREQ"
FREQ_RX="FREQ_RX"

GRIDSQUARE="GRIDSQUARE"
GRIDSQUARE_EXT="GRIDSQUARE_EXT"
GUEST_OP="GUEST_OP"

HAMLOGEU_QSO_UPLOAD_DATE="HAMLOGEU_QSO_UPLOAD_DATE"
HAMLOGEU_QSO_UPLOAD_STATUS="HAMLOGEU_QSO_UPLOAD_STATUS"
HAMQTH_QSO_UPLOAD_DATE="HAMQTH_QSO_UPLOAD_DATE"
HAMQTH_QSO_UPLOAD_STATUS="HAMQTH_QSO_UPLOAD_STATUS"
HRDLOG_QSO_UPLOAD_DATE="HRDLOG_QSO_UPLOAD_DATE"
HRDLOG_QSO_UPLOAD_STATUS="HRDLOG_QSO_UPLOAD_STATUS"

IOTA="IOTA"
IOTA_ISLAND_ID="IOTA_ISLAND_ID"
ITUZ="ITUZ"

K_INDEX="K_INDEX"

LAT="LAT"
LON="LON"
LOTW_QSLRDATE="LOTW_QSLRDATE"
LOTW_QSLSDATE="LOTW_QSLSDATE"
LOTW_QSL_RCVD="LOTW_QSL_RCVD"
LOTW_QSL_SENT="LOTW_QSL_SENT"

MAX_BURSTS="MAX_BURSTS"
MODE="MODE"
MS_SHOWER="MS_SHOWER"
MY_ALTITUDE="MY_ALTITUDE"
MY_ANTENNA="MY_ANTENNA"
MY_ANTENNA="MY_ANTENNA_INTL"
MY_ARRL_SECT="MY_ARRL_SECT"
MY_CITY="MY_CITY"
MY_CITY_INTL="MY_CITY_INTL"
MY_CNTY="MY_CNTY"
MY_COUNTRY="MY_COUNTRY"
MY_COUNTRY_INTL="MY_COUNTRY_INTL"
MY_CQ_ZONE="MY_CQ_ZONE"
MY_DXCC="MY_DXCC"
MY_FISTS="MY_FISTS"
MY_GRIDSQUARE="MY_GRIDSQUARE"
MY_GRIDSQUARE_EXT="MY_GRIDSQUARE_EXT"
MY_IOTA="MY_IOTA"
MY_IOTA_ISLAND_ID="MY_IOTA_ISLAND_ID"
MY_ITU_ZONE="MY_ITU_ZONE"
MY_LAT="MY_LAT"
MY_LON="MY_LON"
MY_NAME="MY_NAME"
MY_NAME_INTL="MY_NAME_INTL"
MY_POSTAL_CODE="MY_POSTAL_CODE"
MY_POSTAL_CODE_INTL="MY_POSTAL_CODE_INTL"
MY_POTA_REF="MY_POTA_REF"
MY_RIG="MY_RIG"
MY_RIG_INTL="MY_RIG_INTL"
MY_SIG="MY_SIG"
MY_SIG_INTL="MY_SIG_INTL"
MY_SIG_INFO="MY_SIG_INFO"
MY_SIG_INFO_INTL="MY_SIG_INFO_INTL"
MY_SOTA_REF="MY_SOTA_REF"
MY_STATE="MY_STATE"
MY_STREET="MY_STREET"
MY_STREET_INTL="MY_STREET_INTL"
MY_USACA_COUNTIES="MY_USACA_COUNTIES"
MY_VUCC_GRIDS="MY_VUCC_GRIDS"
MY_WWFF_REF="MY_WWFF_REF"

NAME="NAME"
NAME_INTL="NAME_INTL"
NOTES="NOTES"
NOTES_INTL="NOTES_INTL"
NR_BURSTS="NR_BURSTS"
NR_PINGS="NR_PINGS"

OPERATOR="OPERATOR"
OWNER_CALLSIGN="OWNER_CALLSIGN"

PFX="PFX"
POTA_REF="POTA_REF"
PRECEDENCE="PRECEDENCE"
PROP_MODE="PROP_MODE"
PUBLIC_KEY="PUBLIC_KEY"

QRZCOM_QSO_UPLOAD_DATE="QRZCOM_QSO_UPLOAD_DATE"
QRZCOM_QSO_UPLOAD_STATUS="QRZCOM_QSO_UPLOAD_STATUS"
QSLMSG="QSLMSG"
QSLMSG_INTL="QSLMSG_INTL"
QSLRDATE="QSLRDATE"
QSLSDATE="QSLSDATE"
QSL_RCVD="QSL_RCVD"
QSL_RCVD_VIA="QSL_RCVD_VIA"
QSL_SENT="QSL_SENT"
QSL_SENT_VIA="QSL_SENT_VIA"
QSL_VIA="QSL_VIA"
QSO_COMPLETE="QSO_COMPLETE"
QSO_DATE="QSO_DATE"
QSO_DATE_OFF="QSO_DATE_OFF"
QSO_RANDOM="QSO_RANDOM"
QTH="QTH"
QTH_INTL="QTH_INTL"

REGION="REGION"
RIG="RIG"
RIG_INTL="RIG_INTL"
RST_RCVD="RST_RCVD"
RST_SENT="RST_SENT"
RX_PWR="RX_PWR"

SAT_MODE="SAT_MODE"
SAT_NAME="SAT_NAME"
SFI="SFI"
SIG="SIG"
SIG_INTL="SIG_INTL"
SIG_INFO="SIG_INFO"
SIG_INFO_INTL="SIG_INFO_INTL"
SILENT_KEY="SILENT_KEY"
SKCC="SKCC"
SOTA_REF="SOTA_REF"
SRX="SRX"
SRX_STRING="SRX_STRING"
STATE="STATE"
STATION_CALLSIGN="STATION_CALLSIGN"
STX="STX"
STX_STRING="STX_STRING"
SUBMODE="SUBMODE"
SWL="SWL"

TEN_TEN="TEN_TEN"
TIME_OFF="TIME_OFF"
TIME_ON="TIME_ON"
TX_PWR="TX_PWR"

UKSMG="UKSMG"
USACA_COUNTIES="USACA_COUNTIES"

VE_PROV="VE_PROV"
VUCC_GRIDS="VUCC_GRIDS"

WEB="WEB"
WWFF_REF="WWFF_REF"

# QRZ Fields for Callsign lookup
QRZ_CALL = "call"
QRZ_ALIASES ="aliases"
QRZ_DXCC="dxcc" 
QRZ_FNAME="fname" 
QRZ_NAME="name" 
QRZ_ADDR1="addr1" 
QRZ_ADDR2="addr2" 
QRZ_STATE="state" 
QRZ_ZIP="zip" 
QRZ_COUNTRY="country" 
QRZ_CCODE="ccode" 
QRZ_LAT="lat" 
QRZ_LON="lon" 
QRZ_GRID="grid" 
QRZ_COUNTY="county" 
QRZ_FIPS="fips" 
QRZ_LAND="land" 
QRZ_EFDATE="efdate" 
QRZ_EXPDATE="expdate" 
QRZ_P_CALL="p_call" 
QRZ_CLASS="class" 
QRZ_CODES="codes" 
QRZ_QSLMSGR="qslmgr" 
QRZ_EMAIL="email" 
QRZ_URL="url" 
QRZ_U_VIEWS="u_views" 
QRZ_BIO="bio" 
QRZ_IMAGE="image" 
QRZ_SERIAL="serial" 
QRZ_MODDATE="moddate" 
QRZ_MSA="MSA" 
QRZ_AREACODE="AreaCode" 
QRZ_TIMEZONE="TimeZone" 
QRZ_GMTOFFSET="GMTOffset" 
QRZ_DST="DST" 
QRZ_EQSL="eqsl" 
QRZ_MQSL="mqsl" 
QRZ_CQZONE="cqzone" 
QRZ_ITUZONE="ituzone" 
QRZ_GEOLOC="geoloc" 
QRZ_ATTN="attn" 
QRZ_NICKNAME="nickname" 
QRZ_FMT="name_fmt" 
QRZ_BORN="born" 
QRZ_ERROR="Error"

# QRZ configuration strings
QRZ_USERNAME = "QRZ_USERNAME"
QRZ_PASSWORD = "QRZ_PASSWORD"

# Global configuration strings
MY_CALLSIGN = "MY_CALLSIGN"
MY_NAME="MY_NAME"
MY_COUNTRY="MY_COUNTRY"
#MY_STATE="MY_STATE" configured above
MY_GRID="MY_GRID"
CURRENT_LOGBOOK="CURRENT_LOGBOOK"
QSO_ID = "QSO_ID"

# BANDS
bands={'2190m':(135700,137800),
       '630m':(472000,479000),
       '560m':(501000,504000),
       '160m':(1800000,2000000),
       '80m':(3500000,4000000),
       '60m':(5060000,5450000),
       '40m':(7000000,7300000),
       '30m':(10100000,10150000),
       '20m':(14000000,14350000),
       '17m':(18068000,18168000),
       '15m':(21000000,21410000),
       '12m':(24890000,24900000),
       '10m':(28000000,29700000),
       '8m':(40000000,45000000),
       '6m':(50000000,54000000),
       '4m':(70000000,74000000),
       '2m':(144000000,148000000),
       '1.25m':(222000000,225000000),
       '70cm':(420000000,450000000),
       '33cm':(902000000,928000000),
       '23cm':(1240000000,1300000000),
       '13cm':(2300000000,2450000000),
       '9cm':(3300000000,3500000000),
       '6cm':(5650000000,5925000000),
       '3cm':(10000000000,10500000000),
       '1.25cm':(24000000000,24250000000),
       '6mm':(47000000000,47200000000),
       '4mm':(75500000000,81000000000),
       '2.5mm':(119980000000,123000000),
       '2mm':(134000000000,149000000000),
       '1mm':(241000000000,250000000000),
       'submm':(300000000000,7500000000000)
       }

modes = ['USB','LSB','CW','FT8','OLIVIA','PSK31','RTTY','SSTV','JS8CALL','DMR','C4FM','DSTAR','M17','PACKET']